permissions:
  RELOAD_PERM: "aevycore.reload"

messages:
  PREFIX: "&b AevyCore &7» "
  SUCCESS: "&a"
  ERROR: "&c"
  NORMAL: "&f"
  errors:
    NO_PERMS: "You can't execute this command!"
    NO_PLAYER: "You can't execute this command as a player!"
    NO_CONSOLE: "You can't execute this command as the console!"

commands:
  RELOAD_MESSAGE: "Configuration has been reloaded!"

database:
  DRIVER: "org.mariadb.jdbc.Driver"
  URL: "mariadb"
  IP: "localhost"
  PORT: "3306"
  USER: "root"
  PASSWORD: "root"
  DATABASE: "aevy-core"
  MAX_POOL_SIZE: 6
  DEBUG: true
  PROPERTIES: []
  USE_DEFAULTS: true