name: AevyCore
version: '${project.version}'
main: fun.aevy.aevycore.AevyCore
authors: [ Sorridi ]
description: Core API plugin
website: https://github.com/AevyDevs/AevyCore
api-version: 1.18
commands:
  corereload:
    description: Reload the configuration.
  coreversion:
    description: Prints the current version.